### ISSUE TITLE
Failed to create /system.slice/

### ISSUE THREAD

**Issue by mwoodpatrick** [trfore/docker-debian12-systemd#14]
I would like to be able to run systemd in a Debian container and saw this repo. I am running with an Ubuntu 22.04 distro on the latest WSL-2 on Windows 11. When I pull or build the image and run it using the command line specified the container:

`docker run -d -it --name debian12-systemd --privileged --cgroupns=host --tmpfs=/run --tmpfs=/tmp --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro trfore/docker-debian12-systemd:latest`

The container immediately exits and the docker log shows the message below. I would appreciate any pointers on how to fix this issue and any pointers you know of on running containers with systemd.

```
docker logs debian12-systemd
systemd 252.19-1~deb12u1 running in system mode (+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization wsl.
Detected architecture x86-64.

Welcome to Debian GNU/Linux 12 (bookworm)!

Failed to create /system.slice/docker-7ff9a6ce26b54d1174c7b19f1091aa18e8b6244b5f5efc01cdca810f102ad23e.scope/init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
```

**Comment by artakvg** [comment]
same for me , ubuntu 22 and debian 12 are not working
